/** Giyim kategorisi ürün verisi — giyim.js ve urun-detay.js tarafından kullanılır */
window.GIYIM_PRODUCTS = [
  { id: 1, title: 'Basic Tişört', brand: 'Marka A', price: 149.99, priceOld: 199.99, discount: 25, rating: 4.2, reviewCount: 12, salesCount: 120, img: '', link: 'urun-detay.html?id=1', description: 'Günlük kullanım için pamuklu basic tişört.', specs: { 'Materyal': 'Pamuk', 'Beden': 'S, M, L, XL' }, stock: 15, beden: ['S','M','L','XL'], renk: ['siyah','beyaz','mavi','gri'] },
  { id: 2, title: 'Slim Fit Pantolon', brand: 'Marka B', price: 299, priceOld: 349, discount: 14, rating: 4.5, reviewCount: 8, salesCount: 85, img: '', link: 'urun-detay.html?id=2', description: 'Slim fit kesim erkek pantolon.', specs: { 'Materyal': 'Kot', 'Beden': '28-38' }, stock: 8, beden: ['28','30','32','34','36','38'], renk: ['siyah','mavi','gri'] },
  { id: 3, title: 'Sweatshirt Kapüşonlu', brand: 'Marka A', price: 399, priceOld: 499, discount: 20, rating: 4.8, reviewCount: 24, salesCount: 200, img: '', link: 'urun-detay.html?id=3', description: 'Kapüşonlu sweatshirt.', specs: { 'Materyal': 'Pamuk', 'Beden': 'S, M, L, XL' }, stock: 12, beden: ['S','M','L','XL'], renk: ['siyah','gri','beyaz'] },
  { id: 4, title: 'Jean Ceket', brand: 'Marka C', price: 599, priceOld: 699, discount: 14, rating: 4.3, reviewCount: 6, salesCount: 45, img: '', link: 'urun-detay.html?id=4', description: 'Klasik jean ceket.', specs: { 'Materyal': 'Denim', 'Beden': 'S, M, L' }, stock: 5, beden: ['S','M','L'], renk: ['mavi','siyah'] },
  { id: 5, title: 'Kot Şort', brand: 'Marka B', price: 199, priceOld: 249, discount: 20, rating: 4, reviewCount: 15, salesCount: 90, img: '', link: 'urun-detay.html?id=5', description: 'Yazlık kot şort.', specs: { 'Materyal': 'Kot', 'Beden': 'S, M, L' }, stock: 20, beden: ['S','M','L'], renk: ['mavi','siyah'] },
  { id: 6, title: 'Polo Yaka T-Shirt', brand: 'Marka A', price: 179, priceOld: 229, discount: 22, rating: 4.6, reviewCount: 31, salesCount: 150, img: '', link: 'urun-detay.html?id=6', description: 'Polo yaka günlük tişört.', specs: { 'Materyal': 'Pamuk', 'Beden': 'S, M, L, XL' }, stock: 25, beden: ['S','M','L','XL'], renk: ['beyaz','mavi','siyah'] }
];
